baseURL = "https://example.com"
languageCode = "en-us"
title = "Nemath Ahmed"
theme = "cactus"
copyright = "Nemath Ahmed" # cactus will use title if copyright is not set
disqusShortname = "nemath" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Pixel Pie Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4



[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Hi, I'm Nemath. Welcome to my webpage. I'm a final year undergraduate about to graduate in July 2021 majoring in Electrical Engineering at Indian Institute of Techonology, Indore. I have been working with <a href=\"https://cfaed.tu-dresden.de/\">Center For Advanced Electronics Dresden</a> since Jan 2021 for my thesis under <a href=\"https://cfaed.tu-dresden.de/pd-staff-kumar\">Prof. Akash Kumar</a> where my work revolves around Reinforcement Learning. I have also worked at the intersection of Software Development, Human Computer Interaction, Computer Vision, and Deep Learning during my time at <a href=\"https://www.ntu.edu.sg/\">NTU Singapore</a>, <a href=\"https://dozee.io/\">Dozee Research</a> and <a href=\"https://www.drdo.gov.in/labs-and-establishments/institute-nuclear-medicine-allied-sciences-inmas\">DRDO</a>."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true # default
  # postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/nemathahmed"
  [[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/nemathahmed"
  [[params.social]]
    name = "github"
    link = "https://github.com/nemathahmed"
  [[params.social]]
    name = "email"
    link = "nemath.ahmed14@gmail.com"  # no need for "mailto:" in the head
